import { MenuItem, Category, Testimonial, Staff, Location, Gallery } from '@/types';
import { Pizza } from 'lucide-react';

export const menuItems: MenuItem[] = [
  {
    id: 2,
    name: 'Turkish Breakfast For Two Person',
    description: "ss",
    price: '₺1250',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/IKI-KISILIK-SERPME-KAHVALTI-.webp',
    category: 'Breakfast',
    featured: false,
  },
  {
    id: 3,
    name: 'EGGS WITH GOLAB PARIS SAUCE',
    description: 'Beef bacon on English muffins, 2 poached eggs, and hollandaise sauce served with chives baked side salad',
    price: '₺480',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/GOLAB-PARIS-SOSLU-YUMURTA.webp',
    category: 'Breakfast',
    featured: false,
  },
  {
    id: 4,
    name: 'Breakfast Plate',
    description: 'Ezine feta cheese, Kars cheddar, Chengelkoy cucumber, tomato, honey, cherry jam, Nutella, boiled egg, bread basket, Served with 2 teas.',
    price: '₺550',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/KAHVALTI-TABAGI.webp',
    category: 'Breakfast',
    featured: false,
  },
  {
    id: 5,
    name: 'AVOCADO POACHED EGGS',
    description: 'Served with avocado toast, 2 poached eggs, chives, side salad',
    price: '₺450',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/AVOKADO-POSE-YUMURTA.webp',
    category: 'Breakfast',
    featured: false,
  },
  {
    id: 6,
    name: 'Menemen',
    description: 'egg, tomato',
    price: '₺280',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/MENEMEN.webp',
    category: 'Breakfast',
    featured: false,
  },
  {
    id: 8,
    name: 'FRENCH OMELET',
    description: 'Served with plain cheese and mushroom salad',
    price: '₺350',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/FRANSIZ-OMLET.webp',
    category: 'Breakfast',
    featured: false,
  },
  {
    id: 9,
    name: 'PANCAKE',
    description: 'Three layers of fruit and Nutella in four pancake slices',
    price: '₺350',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/PANCAKE.webp',
    category: 'Breakfast',
    featured: false,
  },
  {
    id: 10,
    name: 'FRIED EGGS WITH SUSAUS',
    description: 'Cheddar cheese with Sausage',
    price: '₺290',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/SAHANDA-YUMURTA-SUCUKLU.webp',
    category: 'Breakfast',
    featured: false,
  },
  {
    id: 11,
    name: 'FRIED EGGS',
    description: 'Fried eggs',
    price: '₺200',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/SAHANDA-YUMURTA.webp',
    category: 'Breakfast',
    featured: false,
  },
  {
    id: 12,
    name: 'FRIED EGGS WITH cheddar CHEESE',
    description: 'FRIED EGGS WITH cheddar CHEESE',
    price: '₺250',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/SAHANDA-YUMURTA.webp',
    category: 'Breakfast',
    featured: false,
  },
  {
    id: 13,
    name: 'FRIED EGG WITH CHEESE',
    description: 'Fried eggs with cheese',
    price: '₺200',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/SAHANDA-YUMURTA.webp',
    category: 'Breakfast',
    featured: false,
  },

  {
    id: 15,
    name: 'CHEESE PLATE',
    description: 'three types of cheese',
    price: '₺450',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/PEYNIR-TABAGI.webp',
    category: 'Breakfast',
    featured: false,
  },
  // Appetizers
  {
    id: 16,
    name: 'LENTIL SOUP',
    description: 'Lentil soup, Lemon, Kruton',
    price: '₺190',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/MERCIMEK-CORBASI.webp',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 17,
    name: '10 SIGNATURE MEZES',
    description: "Chef's suggestion",
    price: '₺1550',
    image: 'https://golabrestaurant.com/wp-content/uploads/2025/04/10LU.jpeg',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 18,
    name: "Golab Chef's Mezzes",
    description: "Chef's suggestion",
    price: '₺950',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/GOLAB-SEFIN-MEZELERI.webp',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 19,
    name: 'STUFFED MUSSELS',
    description: 'Seafood rice, edible mussel shell chips, lime',
    price: '₺500',
    image: 'https://golabrestaurant.com/wp-content/uploads/2025/04/midye-dolma-1.jpeg',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 20,
    name: 'HUMMUS WITH PASTRAMI',
    description: 'Crispy pastrami, crispy chickpeas, hummus, red oil',
    price: '₺500',
    image: 'https://golabrestaurant.com/wp-content/uploads/2025/04/humus-1.jpeg',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 21,
    name: 'AEGEAN HERB SAUTE',
    description: 'Aegean herbs, caramelized onion, strained yogurt, sliced almonds, red oil',
    price: '₺450',
    image: 'https://golabrestaurant.com/wp-content/uploads/2025/04/EGG-OT-1.jpeg',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 22,
    name: 'SHRIMP IN BUTTER ',
    description: 'Shrimp, red bell pepper, village pepper, mushrooms, spring onion, sesame, butter',
    price: '₺650',
    image: 'https://golabrestaurant.com/wp-content/uploads/2025/04/KARIDES-1.jpeg',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 23,
    name: 'MEDETERRANEAN DELIGHT',
    description: 'Mediterranean fish balls, sweet chili, green oil, soybean sprouts',
    price: '₺600',
    image: 'https://golabrestaurant.com/wp-content/uploads/2025/04/LOKUM-1.jpeg',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 24,
    name: 'APPETIZER PLATE',
    description: 'Appetizer Plate',
    price: '₺700',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/MEZE-TABAGI.webp',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 25,
    name: 'Beer Plate',
    description: 'Beer Plate',
    price: '580',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/MERCIMEK-CORBASI.webp',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 26,
    name: 'Golab Cheese Plate',
    description: 'Golab Cheese Plate',
    price: '1100',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/Golab-Peynir-Tabagi.webp',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 27,
    name: 'pacanga BALLS',
    description: 'Fried paçanga balls with bacon and mozzarella, Sweet chili sauce',
    price: '₺650',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/PACANGA-TOPLARI.webp',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 28,
    name: 'HUMUS',
    description: 'Chickpea chips, Tomato, Arugula, Pickled onion, Pepper oil',
    price: '₺300',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/HUMUS.webp',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 29,
    name: 'KASHKE BADEMJAN',
    description: 'Fried eggplant, Fried onion, Kashk cheese, Mint oil',
    price: '₺300',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/KASHKE-BADEMJAN.webp',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 30,
    name: ' French Fries',
    description: 'Fries Potato',
    price: '₺250',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/PATATES-KIZARTMASI.webp',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 31,
    name: 'MIRZA GHASSEMİ',
    description: 'Roasted eggplant, Garlic, Grilled Tomato, Egg, Quail egg',
    price: '₺270',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/MIRZA-GHASSEMI.webp',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 32,
    name: 'ZEYTIN PARVARDE',
    description: 'Green olives, garlic, walnut, pomegranate',
    price: '₺350',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1685781795-e1727424189584.jpeg',
    category: 'Appetizers',
    featured: false,
  },
  {
    id: 33,
    name: 'Yogurt',
    description: 'Types of Yogurt:Yogurt and cucumber, Garlic Yogurt, Eggplant Yogurt',
    price: '₺130',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/Yogurt-Cesitleri.webp',
    category: 'Appetizers',
    featured: false,
  },
  // Salads
  {
    id: 34,
    name: 'CHICKEN CAESAR SALAD',
    description: 'Grilled Chicken, Lettuce, Kruton, Caesar Sauce',
    price: '₺550',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1678501504-e1727430221713.jpg',
    category: 'Salads',
    featured: false,
  },
  {
    id: 35,
    name: 'GREEN SALAD',
    description: 'Arugula, Green Apple and Crunchy Walnuts, Rice Vinegar, Pomegranate, Orange and Cucumber',
    price: '₺550',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1678501800-e1727429681394.jpg',
    category: 'Salads',
    featured: false,
  },
  {
    id: 36,
    name: 'SHIRAZI SALAD',
    description: 'Cucumber, Tomato, Onion, Lemon juice',
    price: '₺170',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1685783228.jpg',
    category: 'Salads',
    featured: false,
  },
  {
    id: 37,
    name: 'TULUM CHEESE SHEPHERD SALAD',
    description: 'Colorful Tomatoes, Cucumber, Green pepper, California pepper, Red pepper, Purple Onion, Basil, Lemon vinepret',
    price: '₺490',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1678501981-e1727429631208.jpg',
    category: 'Salads',
    featured: false,
  },
  // Main Course
  {
    id: 38,
    name: 'SALMON',
    description: 'Pea puree, avocado, purslane, fennel, strawberry, capers, blackcurrant, green oil, lemon saffron sauce, plum',
    price: '₺950',
    image: 'https://golabrestaurant.com/wp-content/uploads/2025/04/SOMON.jpeg',
    category: 'Main Course',
    featured: false,
  },
  {
    id: 39,
    name: 'CAFÉ DE PARIS ENTRECOTE WITH SAUCE',
    description: 'Café de Paris sauce, oven-baked tomatoes, baby potatoes, fresh thyme (Beef entrecôte)',
    price: '₺950',
    image: 'https://golabrestaurant.com/wp-content/uploads/2025/04/cafede.jpeg',
    category: 'Main Course',
    featured: false,
  },
  {
    id: 40,
    name: 'KUZU LOKUM',
    description: 'Plum, caramelized tomatoes, baby potatoes, purslane salad, demi-glace sauce',
    price: '₺1100',
    image: 'https://golabrestaurant.com/wp-content/uploads/2025/04/Lokum-main.jpeg',
    category: 'Main Course',
    featured: false,
  },
  {
    id: 41,
    name: 'SEA BASS',
    description: 'Fondant potato, fennel, purslane, lime, chimichurri sauce, baby radish, green oil',
    price: '₺850',
    image: 'https://golabrestaurant.com/wp-content/uploads/2025/04/LEVREK-1.jpg',
    category: 'Main Course',
    featured: false,
  },
  {
    id: 42,
    name: 'CHICKEN TANDORI',
    description: 'Marinated chicken breast, Basmati Rice, Tomato Coriander Salad, Lavash, Grilled Lemon',
    price: '₺550',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/86de7f_2f82f8ba84ca437ebd80a376c2d31987mv2-e1727431414691.jpg',
    category: 'Main Course',
    featured: false,
  },
  // Iranian Dishes
  {
    id: 43,
    name: 'SINI MAKHSOOS',
    description: 'Loghme kebab, a boneless barbecue chicken, a shishlik kebab, a muscle or neck plate',
    price: '₺3890',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/DSC00410-1.jpg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 44,
    name: 'Golab Special',
    description: 'Golab Special',
    price: '₺1550',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/01/EZ_00189-2-e1727434073329.jpg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 45,
    name: 'SOLTANI KEBAB',
    description: 'A Shish Kubide And A Shish Berg Kebab',
    price: '₺1670',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/SOLTANI-KEBAB-scaled.jpg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 46,
    name: 'SHISHLIK',
    description: 'Grilled Lamb Chops',
    price: '₺1640',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1685785365.jpg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 47,
    name: 'BARG',
    description: 'Grilled Beef Tenderloin with Special Sauce.',
    price: '₺1150',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/01/IMG_3258-1.jpg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 48,
    name: 'LOGHME',
    description: 'Ground beef and lamb, onions Iranian food',
    price: '₺590',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1685784861.jpg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 49,
    name: 'JUJE BI OSTOKHAN',
    description: 'Boneless Chicken ',
    price: '₺590',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1681677343-e1727434880856.jpg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 50,
    name: 'GARDAN',
    description: "Lamb's neck",
    price: '₺1150',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/05/photo1715539058.jpeg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 51,
    name: 'MAHICHE',
    description: 'Lamb shank',
    price: '₺1150',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1676972322.jpg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 52,
    name: 'GHORME SEBZİ',
    description: 'A mixture of fresh meat, dense vegetables and red beans, Iranian Cuisine',
    price: '₺510',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1674485403-1.jpg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 53,
    name: 'GHEYMEH',
    description: 'Fresh Meat, Some Kind of Chickpea, Onion, Tomato Paste And Fried Potato.',
    price: '₺460',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1674485344-1.jpg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 54,
    name: 'GHEYMEH BADEMJAN',
    description: 'Eggplant, Fresh Meat, A Kind of Chickpea, Onion, Tomato Paste And Fried Potatoes.',
    price: '₺460',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1674485497-1.jpg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 55,
    name: 'ZERESHK POLO BA MORGH',
    description: 'Persian rice, chicken with sauce, zeresk iranian Cuisine',
    price: '₺650',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1678505327-e1727435183601.jpg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 56,
    name: 'Baghali Polo',
    description: 'broad beans, dill',
    price: '₺195',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/05/photo1715539045.jpeg',
    category: 'Iranian Dishes',
    featured: false,
  },
  {
    id: 57,
    name: 'IRANIAN RICE WITH SAFRAN',
    description: 'IRANIAN RICE WITH SAFRAN',
    price: '₺190',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1677970237.jpg',
    category: 'Iranian Dishes',
    featured: false,
  },
  // Pizza
  {
    id: 58,
    name: 'MIX PIZZA',
    description: 'Pizza dough, Pizza sauce, Pepperoni, sausage, Roasted beef bacon, Colorful peppers, Mushroom, Olive',
    price: '₺750',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/10/Mix-Pizza.webp',
    category: 'Pizza',
    featured: false,
  },
  {
    id: 59,
    name: 'GARLIC WITH MEAT',
    description: 'Pizza dough, Pizza Sauce, Tenderloin Slices, Pickled cucumber, Roasted capia pepper, Garlic Mayonnaise, Parsley',
    price: '₺700',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/10/ETLI-SARIMSAKLI-PIZZA-meet-garlic-pizza.webp',
    category: 'Pizza',
    featured: false,
  },
  {
    id: 60,
    name: 'MARGARITA',
    description: 'Pizza dough, Pizza sauce, Pesto sauce, Mozzarella, Arugula',
    price: '₺450',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/10/MARGARITA-PIZZA.webp',
    category: 'Pizza',
    featured: false,
  },
  // Burger
  {
    id: 61,
    name: 'GOLAB BURGER',
    description: 'Burger is served with sauce, caramelized onions, lettuce, tomato, pickles, and french fries.',
    price: '₺900',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/GOLAB-BURGER.webp',
    category: 'Burgers',
    featured: false,
  },
  {
    id: 62,
    name: 'SMOKED BURGER',
    description: 'Burger is served with sauce, caramelized onions, lettuce, tomato, pickles, and french fries.',
    price: '₺650',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/FUME-ETLI-BURGER.webp',
    category: 'Burgers',
    featured: false,
  },
  {
    id: 63,
    name: 'CHICKEN BURGER',
    description: 'Served with marinated crispy chicken breast, coleslaw salad, cheddar, burger sauce, and french fries.',
    price: '₺500',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/TAVUK-BURGER.webp',
    category: 'Burgers',
    featured: false,
  },
  // Pasta
  {
    id: 64,
    name: 'Pesto Fettuccine with Chicken',
    description: 'Grilled Chicken Breast, Basil Pesto, Walnuts and Parmesan',
    price: '₺580',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/PESTO-SOSLU-Fettuccine-Tavuklu.webp',
    category: 'Pasta',
    featured: false,
  },
  {
    id: 65,
    name: 'TAGLIATELLE ALFREDO with Chicken',
    description: 'Grilled chicken breast, Tagliatelle pasta, parmesan, cream, mushroom, basil, butter',
    price: '₺500',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/TAGLIATELLE-ALFREDO-TAVUKLU.webp',
    category: 'Pasta',
    featured: false,
  },
  // Deserts
  {
    id: 66,
    name: 'FRUIT PLATE',
    description: 'FRUIT PLATE',
    price: '₺600',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/img_1472_1685746866-1_edited_edited_edited.jpg',
    category: 'Deserts',
    featured: false,
  },
  {
    id: 67,
    name: 'SAN SEBASTIAN CHEESECAKE',
    description: 'San Sebastian Cheesecake, Belgian Chocolate',
    price: '₺380',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/IMG_1554-scaled.jpg',
    category: 'Deserts',
    featured: false,
  },
  {
    id: 68,
    name: 'TIRAMISU',
    description: 'Tiramisu cream, biscuits, Espresso, Granulated Coffee, Cocoa',
    price: '₺395',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/TIRAMISU.webp',
    category: 'Deserts',
    featured: false,
  },
  {
    id: 69,
    name: 'Strawberry puff pastry',
    description: 'Pastry cream, Puff pastry wafer, Powdered sugar, Strawberry',
    price: '₺380',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/CILEKLI-MILFOY-1.webp',
    category: 'Deserts',
    featured: false,
  },
  {
    id: 70,
    name: 'Profiterole',
    description: 'Pastry cream, melted belgian chocolate',
    price: '₺380',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/Profiterol.webp',
    category: 'Deserts',
    featured: false,
  },
  {
    id: 71,
    name: 'Suffle',
    description: 'Suffle, Ice Cream, Strawberry',
    price: '₺380',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/SUFLE.webp',
    category: 'Deserts',
    featured: false,
  },
  {
    id: 72,
    name: 'DONDURMA',
    description: 'ice creem (3 scoop)',
    price: '₺240',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DONDURMA.webp',
    category: 'Deserts',
    featured: false,
  },
  // Cocktails
  {
    id: 73,
    name: 'LONG ISLAND',
    description: 'vodka, gin, white rum, tequila , coca , orange juice',
    price: '₺470',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00598-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 74,
    name: 'MARGARITA',
    description: 'Tequila, orange liqueur, lemon peel',
    price: '₺430',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00465-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 75,
    name: 'MARTINI',
    description: 'Gin, Vermouth',
    price: '₺430',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00405-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 76,
    name: 'ESPRESSO MARTINI',
    description: 'vodka, cream, coffee liqueur',
    price: '₺430',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00505-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 77,
    name: 'BIKINI MARTINI',
    description: 'malibu, vodka, pineapple juice, granadian syrup',
    price: '₺430',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00342-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 78,
    name: ' REAL MOJITO',
    description: 'white rum, lemon juice, mint, soda , syrup',
    price: '₺400',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00709-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 79,
    name: 'NEW YORK SOUR',
    description: 'cherry wine, whiskey , white egg , lemon juice , syrup',
    price: '₺430',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00487-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 80,
    name: 'SUMMER TIME',
    description: 'tequila, limoncello, sweet & sour, lemon juice, basil, salt',
    price: '₺430',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00594-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 81,
    name: 'Spicy margarita',
    description: 'Tequila , triple sec , lime juice , jalapeno pepper',
    price: '₺430',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00621-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 82,
    name: 'Negroni',
    description: 'Gin , campari , red vermouth, orange',
    price: '₺430',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00344-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 73,
    name: 'LONG ISLAND',
    description: 'vodka, gin, white rum, tequila , coca , orange juice',
    price: '₺470',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00598-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 74,
    name: 'OLD FASHIONED',
    description: 'Bourbon Whiskey, Angostura Bitter, Sugar',
    price: '₺430',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00465-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 75,
    name: 'SATANIC',
    description: 'Vodka, Lavash, Blueberry, Lemon Juice, Salt',
    price: '₺430',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00465-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 76,
    name: 'GOLAB SPECIAL',
    description: 'Vodka, Vermouth, Saffron Syrup, Egg Whites, Lemon Juice',
    price: '₺550',
    image: 'https://golabrestaurant.com/wp-content/uploads/2024/09/DSC00465-scaled.jpg',
    category: 'Cocktails',
    featured: false,
  },
  {
    id: 77,
    name: 'GIN AND TONIK',
    description: 'Gin, Tonik water',
    price: '₺430',
    image: 'https://golabrestaurant.com/wp-content/uploads/2023/10/76b600_6eb94d6e00ac44329c2e29619-e1720716038141.jpg',
    category: 'Cocktails',
    featured: false,
  },


  
];

export const categories: Category[] = [
  {
    id: 1,
    name: 'Breakfast',
    description: "Start your day with our delicious breakfast options.",
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 2,
    name: 'Appetizers',
    description: 'Start your meal with our delicious bite-sized starters.',
    image: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 3,
    name: 'Main Course',
    description: 'Authentic dishes prepared with traditional recipes and fresh ingredients.',
    image: 'https://images.pexels.com/photos/7625056/pexels-photo-7625056.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 4,
    name: 'Iranian Dishes',
    description: 'Aromatic rice dishes cooked to perfection with herbs and spices.',
    image: 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 12,
    name: 'Cocktails',
    description: 'Refreshing alcoholic drinks to accompany your meal.',
    image: 'https://images.pexels.com/photos/14705344/pexels-photo-14705344.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 6,
    name: 'Pizza',
    description: 'Delicious pizza to satisfy your cravings.',
    image: 'https://images.pexels.com/photos/14705344/pexels-photo-14705344.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 7,
    name: 'Burgers',
    description: 'Juicy burgers to satisfy your cravings.',
    image: 'https://images.pexels.com/photos/14705344/pexels-photo-14705344.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 8,
    name: 'Pasta',
    description: 'Creamy pasta to satisfy your cravings.',
    image: 'https://images.pexels.com/photos/14705344/pexels-photo-14705344.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 9,
    name: 'Desserts',
    description: 'Sweet treats to end your meal on a delightful note.',
    image: 'https://images.pexels.com/photos/14705344/pexels-photo-14705344.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 10,
    name: 'Coffee and Tea',
    description: 'Refreshing coffee and tea to accompany your meal.',
    image: 'https://images.pexels.com/photos/14705344/pexels-photo-14705344.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 11,
    name: "Soft Drinks",
    description: 'Refreshing soft drinks to accompany your meal.',
    image: 'https://images.pexels.com/photos/14705344/pexels-photo-14705344.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 5,
    name: 'Salads',
    description: 'Fresh and healthy salads to accompany your meal.',
    image: 'https://images.pexels.com/photos/2474658/pexels-photo-2474658.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 13,
    name: 'Milkshake & Smoothies',
    description: 'Refreshing milkshake and smoothies to accompany your meal.',
    image: 'https://images.pexels.com/photos/14705344/pexels-photo-14705344.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },


];

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: 'Sarah Johnson',
    role: 'Food Enthusiast',
    content: 'The food here is absolutely amazing! The flavors are authentic and the service is exceptional. I highly recommend the Butter Chicken and Garlic Naan.',
    rating: 5,
    image: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 2,
    name: 'David Chen',
    role: 'Regular Customer',
    content: 'GoLab Restaurant has become our family\'s favorite dining spot. The menu offers a great variety and the staff always makes us feel welcome.',
    rating: 5,
    image: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 3,
    name: 'Emily Rodriguez',
    role: 'Food Blogger',
    content: 'As someone who tries new restaurants weekly, I can confidently say that GoLab stands out with its authentic flavors and beautiful presentation. Their biryani is a must-try!',
    rating: 4,
    image: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 4,
    name: 'Michael Thompson',
    role: 'Local Resident',
    content: 'I\'ve been coming here for years and the quality has never disappointed. The owners truly care about providing an exceptional dining experience.',
    rating: 5,
    image: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
];

export const staff: Staff[] = [
  {
    id: 1,
    name: 'Raj Patel',
    role: 'Head Chef',
    bio: 'With over 20 years of experience in authentic cuisine, Chef Raj brings traditional recipes with a modern twist to GoLab Restaurant.',
    image: 'https://images.pexels.com/photos/887827/pexels-photo-887827.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 2,
    name: 'Priya Singh',
    role: 'Restaurant Manager',
    bio: 'Priya ensures that every guest receives a warm welcome and exceptional service during their dining experience at GoLab.',
    image: 'https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 3,
    name: 'Amir Khan',
    role: 'Sous Chef',
    bio: 'Amir specializes in creating innovative dishes that blend traditional flavors with contemporary techniques.',
    image: 'https://images.pexels.com/photos/3814446/pexels-photo-3814446.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
];

export const location: Location = {
  address: '123 Cuisine Street',
  city: 'Flavortown',
  state: 'CA',
  zip: '90210',
  phone: '(555) 123-4567',
  email: 'info@golabrestaurant.com',
  latitude: 34.052235,
  longitude: -118.243683,
  hours: [
    { day: 'Monday', open: '11:00 AM', close: '10:00 PM' },
    { day: 'Tuesday', open: '11:00 AM', close: '10:00 PM' },
    { day: 'Wednesday', open: '11:00 AM', close: '10:00 PM' },
    { day: 'Thursday', open: '11:00 AM', close: '10:00 PM' },
    { day: 'Friday', open: '11:00 AM', close: '11:00 PM' },
    { day: 'Saturday', open: '11:00 AM', close: '11:00 PM' },
    { day: 'Sunday', open: '12:00 PM', close: '9:00 PM' },
  ],
};

export const gallery: Gallery[] = [
  {
    id: 1,
    title: 'Restaurant Interior',
    image: 'https://images.pexels.com/photos/6267/menu-restaurant-vintage-table.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Interior',
  },
  {
    id: 2,
    title: 'Chef Preparing Food',
    image: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Kitchen',
  },
  {
    id: 3,
    title: 'Special Dinner Setting',
    image: 'https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Events',
  },
  {
    id: 4,
    title: 'Signature Dish',
    image: 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Food',
  },
  {
    id: 5,
    title: 'Bar Area',
    image: 'https://images.pexels.com/photos/274192/pexels-photo-274192.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Bar',
  },
  {
    id: 6,
    title: 'Private Dining Room',
    image: 'https://images.pexels.com/photos/775219/pexels-photo-775219.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Interior',
  },
];